### ISSUE TITLE
Index.ctp for Ui template references undefined variable

### ISSUE THREAD

**Issue by bmudda** [alt3/cakephp-swagger#26]
In `cakephp-swagger/src/Template/Ui/index.ctp` file, `$userConfig` should be `$uiConfig`. Currently the **title** field never gets reflected with what is being set in `swagger.php` file because `$userConfig` is not set from the controller, only `$uiConfig` is set.

**Comment by bravo-kernel** [comment]
Nice find mr. @bmudda, feel free to submit a PR

**Comment by bravo-kernel** [comment]
Closing as a PR is now open. #27
