### ISSUE TITLE
Allow to modify API basePath via annotations

### ISSUE THREAD

**Issue by aleks-fofanov** [alt3/cakephp-swagger#29]
Hey,

First of all, thanks for the plugin!

Having the API basePath derived from Configure::read('App.base') is good, but if you have an application where your API endpoints are prefixed (e.g. /api) and this app also serves static content or crud as the webpages this might be an issue.
So, having an option to define API basePath via annotations might help. Basically, if basePath is defined via annotations we use it or App.base otherwise.

The fix is quite trivial but I can create a PR if needed.
Thanks!

**Comment by bravo-kernel** [comment]
I believe you are the second person mentioning this so feel free to submit a PR and we'll take it from there.

**Comment by aleks-fofanov** [comment]
Done #30
